use crate::plugin::AgentPlugin;
use nu_agent_core::config;
use nu_plugin::{EngineInterface, EvaluatedCall, PluginCommand, SimplePluginCommand};
use nu_protocol::{Category, LabeledError, Signature, Value};

/// The `agent config init` command generates a starter config.toml from the
/// current environment variables.
pub struct AgentConfigInit;

impl AgentConfigInit {
    /// Creates a new AgentConfigInit command.
    pub fn new() -> Self {
        Self
    }
}

impl Default for AgentConfigInit {
    fn default() -> Self {
        Self::new()
    }
}

impl SimplePluginCommand for AgentConfigInit {
    type Plugin = AgentPlugin;

    fn name(&self) -> &str {
        "agent config init"
    }

    fn description(&self) -> &str {
        "Generate a starter config.toml from current environment variables"
    }

    fn signature(&self) -> Signature {
        Signature::build(PluginCommand::name(self))
            .switch("force", "Overwrite existing config.toml", None)
            .category(Category::Experimental)
    }

    fn run(
        &self,
        _plugin: &AgentPlugin,
        _engine: &EngineInterface,
        call: &EvaluatedCall,
        _input: &Value,
    ) -> Result<Value, LabeledError> {
        let path = config::toml_config::config_path()
            .map_err(|e| LabeledError::new(format!("Cannot determine config path: {e}")))?;

        let force = call
            .has_flag("force")
            .map_err(|e| LabeledError::new(format!("Failed to check --force flag: {e}")))?;
        if path.exists() && !force {
            return Err(LabeledError::new(format!(
                "config.toml already exists at {}. Use --force to overwrite.",
                path.display()
            )));
        }

        let content = generate_config_content();
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| LabeledError::new(format!("Failed to create config dir: {e}")))?;
        }
        std::fs::write(&path, &content)
            .map_err(|e| LabeledError::new(format!("Failed to write config: {e}")))?;

        Ok(Value::string(
            format!(
                "Created config.toml at {}\n\nEdit it to set your model, then run:\n  agent provider auth login <provider>  (to store API keys)\n  agent models sync              (to fetch model specs)",
                path.display()
            ),
            call.head,
        ))
    }
}

fn generate_config_content() -> String {
    let mut out = String::new();

    // Header
    out.push_str("# nu-agent configuration\n");
    out.push_str("# Generated by `agent config init`\n");
    out.push_str("# Full provider list: run `agent models list`\n");
    out.push_str("# API keys: run `agent provider auth login <provider>` (stored in secrets.json, not here)\n\n");

    // Active config from env vars
    let env_provider = std::env::var("AGENT_PROVIDER").unwrap_or_default();
    let env_model = std::env::var("AGENT_MODEL").unwrap_or_default();

    if !env_provider.is_empty() && !env_model.is_empty() {
        out.push_str("[models.default]\n");
        out.push_str(&format!("model = \"{env_provider}/{env_model}\"\n\n"));
    } else {
        out.push_str("# Edit this to set your default model:\n");
        out.push_str("# [models.default]\n");
        out.push_str("# model = \"ollama-cloud/glm-5.2\"\n\n");
    }

    // Templates
    out.push_str("# ─── Templates ───────────────────────────────────────────\n");
    out.push_str("# Uncomment and fill in for providers you use.\n");
    out.push_str("# API keys are stored in secrets.json via `agent provider auth login`.\n\n");

    out.push_str("# OpenAI\n");
    out.push_str("# [providers.openai]\n");
    out.push_str("# api_key = \"store:openai\"  # run: agent provider auth login openai\n\n");

    out.push_str("# Anthropic\n");
    out.push_str("# [providers.anthropic]\n");
    out.push_str("# api_key = \"store:anthropic\"  # run: agent provider auth login anthropic\n\n");

    out.push_str("# Ollama Cloud\n");
    out.push_str("# [providers.ollama-cloud]\n");
    out.push_str("# provider = \"openai\"\n");
    out.push_str("# base_url = \"https://ollama.com/v1\"\n");
    out.push_str("# api_key = \"store:ollama-cloud\"  # run: agent provider auth login ollama-cloud\n\n");

    out.push_str("# GitHub Copilot (OAuth — no api_key needed)\n");
    out.push_str("# [providers.github-copilot]\n");
    out.push_str("# # run: agent provider auth login github-copilot\n\n");

    out.push_str("# Local Ollama (no auth)\n");
    out.push_str("# [providers.ollama]\n");
    out.push_str("# provider = \"ollama\"\n");
    out.push_str("# base_url = \"http://localhost:11434\"\n\n");

    // Hint to see full list
    out.push_str("# Run `agent models sync` then `agent models list` to see all available providers.\n");

    out
}

#[cfg(test)]
#[path = "init_test.rs"]
mod init_test;
