---
name: nu-agent

path: .

pane_cmd_delay: 2000

windows:
  - name: code
    panes:
      - name: Editor
        flex: 2
        commands:
          - command: nvim
      - name: Harness
        flex: 1
        commands:
          - command: agent
            args:
              - --agent
              - orchestrator
              - --a2a-port
              - 0

  - name: agents
    flex_direction: row
    panes:
      - flex: 1
        commands:
          - command: agent
            args:
              - --agent
              - reviewer
              - --name
              - jack
              - --store
              - jsonl
              - --a2a-port
              - 0
      - flex: 1
        commands:
          - command: agent
            args:
              - --agent
              - researcher
              - --name
              - lucy
              - --store
              - jsonl
              - --a2a-port
              - 0
      - flex: 1
        commands:
          - command: agent
            args:
              - --agent
              - developer
              - --name
              - bob
              - --store
              - jsonl
              - --a2a-port
              - 0
  - name: misc
    flex_direction: row
    panes:
      - flex: 1
      - flex: 1
