[package]
name = "nu_plugin_agent"
edition.workspace = true
version.workspace = true

[[bin]]
name = "nu_plugin_agent"
path = "src/main.rs"

[dependencies]
nu-agent-a2a = { workspace = true }
nu-agent-core = { workspace = true }
nu-agent-tui = { workspace = true }
nu-agent-tty = { workspace = true }
nu-plugin = { workspace = true }
nu-protocol = { workspace = true }
tokio = { workspace = true }
rig = { workspace = true }
crossterm = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
rustls = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
open = "5"
rmcp = { workspace = true }
oauth2 = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
nu-parser = { workspace = true }
serial_test = { workspace = true }
reqwest = { workspace = true }
toml = { workspace = true }
