[package]
name = "nu-agent-tui"
edition.workspace = true
version.workspace = true

[dependencies]
nu-agent-core = { workspace = true }
nu-protocol = { workspace = true }
ratatui = { workspace = true }
ratatui-textarea = { workspace = true }
crossterm = { workspace = true }
unicode-width = { workspace = true }
arboard = { workspace = true }
pulldown-cmark = { workspace = true }
unicodeit = { workspace = true }
libc = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
tempfile = { workspace = true }
