[package]
name = "nu-agent-tui"
edition.workspace = true
version.workspace = true

[dependencies]
nu-agent-core = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
tui-widget-list = { workspace = true }
syntect = { workspace = true }
arboard = { workspace = true }
pulldown-cmark = { workspace = true }
libc = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
tempfile = { workspace = true }
